export enum ApproveScreenType {
  TRANSACTION,
  DECLARE,
  DEPLOY,
  ACCOUNT_DEPLOY,
  MULTISIG_DEPLOY,
  MULTISIG_ADD_SIGNERS,
  MULTISIG_UPDATE_THRESHOLD,
  MULTISIG_REMOVE_SIGNERS,
  MULTISIG_REPLACE_SIGNER,
  MULTISIG_ON_CHAIN_REJECT,
  ADD_GUARDIAN,
  REMOVE_GUARDIAN,
}
