export const ARGENT_SHIELD_ENABLED =
  (process.env.FEATURE_ARGENT_SHIELD || "false") === "true"

export const ARGENT_SHIELD_NETWORK_ID = process.env.ARGENT_SHIELD_NETWORK_ID

export const ARGENT_SHIELD_ERROR_EMAIL_IN_USE =
  "ARGENT_SHIELD_ERROR_EMAIL_IN_USE"
