import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [mintAmount, setMintAmount] = React.useState("10");
  const [transferTo, setTransferTo] = React.useState("");
  const [transferAmount, setTransferAmount] = React.useState("1");

  const handleMintSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log("mint", mintAmount);
  }

  const handleTransferSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    console.log("submit", { transferTo, transferAmount });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Mint token</h2>
        <form onSubmit={handleMintSubmit}>
          <label htmlFor="mint-amount">Amount:</label>
          <br/>
          <input type="text" id="mint-amount" name="fname" value={mintAmount} onChange={e => setMintAmount(e.target.value)} />
          <br/>
          <input type="submit" value="Mint" />
        </form> 

        <h2 className={styles.title} style={{marginTop: 10}}>Transfer token</h2>
        <form onSubmit={handleTransferSubmit}>
          <label htmlFor="transfer-to">To:</label>
          <br/>
          <input type="text" id="transfer-to" name="fname" value={transferTo} onChange={e => setTransferTo(e.target.value)} />
          <br/>
          <label htmlFor="transfer-amount">Amount:</label>
          <br/>
          <input type="text" id="transfer-amount" name="fname" value={transferAmount} onChange={e => setTransferAmount(e.target.value)} />
          <br/>
          <input type="submit" value="Transfer" />
        </form> 
      </main>
    </div>
  )
}

export default Home
