import { ETH_TOKEN_ADDRESS, STRK_TOKEN_ADDRESS } from "../network/constants"

export const FEE_TOKEN_PREFERENCE_BY_ADDRESS = [
  STRK_TOKEN_ADDRESS,
  ETH_TOKEN_ADDRESS,
]

export const FEE_TOKEN_PREFERENCE_BY_SYMBOL = ["STRK", "ETH"]
