import fs from "fs"
import path from "path"

import { transform } from "@svgr/core"
import fetch from "cross-fetch"
import * as dotenv from "dotenv"
import { camelCase, upperFirst } from "lodash"

dotenv.config()

const OUTPUT_FOLDER = path.join(
  __dirname,
  "../src/ui/components/Icons/generated",
)

const FIGMA_ACCESS_TOKEN = process.env.FIGMA_ACCESS_TOKEN
const FIGMA_ICONS_FILE_KEY = "LHwepHSS4bouYQjbMOZJjW"
const FIGMA_ICONS_NODE_ID = decodeURIComponent("0%3A1")

type Components = Record<
  string,
  {
    key: string
    name: string
    description: string
    componentSetId?: string
    documentationLinks: string[]
  }
>

type ComponentSet = Record<
  string,
  {
    key: string
    name: string
    description: string
  }
>

type IconsNode = {
  document: any /** we don't care about this currently */
  components: Components
  componentSets: ComponentSet
}

type ImageResponse = {
  err: null | string
  images: Record<string, string>
}

const svgCodeToIconComponentCode = async (svgCode: string) => {
  return transform(svgCode, {
    icon: true,
    typescript: true,
    jsxRuntime: "automatic",
    replaceAttrValues: { "#fff": "currentColor" },
    plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
  })
}

const fetcher = async (url: string, raw = false) => {
  if (!FIGMA_ACCESS_TOKEN) {
    throw "process.env.FIGMA_ACCESS_TOKEN is not defined - you can get a token from https://www.figma.com/developers/api#access-tokens"
  }
  const response = await fetch(url, {
    method: "GET",
    headers: {
      "X-Figma-Token": FIGMA_ACCESS_TOKEN,
    },
  })
  if (raw) {
    return response
  }
  const json = await response.json()
  return json
}

/** fetch a description of the icon board  which contains the icon ids and names */

const getIconNodesAndNames = async () => {
  const json = await fetcher(
    `https://api.figma.com/v1/files/${FIGMA_ICONS_FILE_KEY}/nodes?ids=${encodeURIComponent(
      FIGMA_ICONS_NODE_ID,
    )}`,
  )
  const iconsNode = Object.values(json.nodes)[0] as IconsNode
  const { components, componentSets } = iconsNode
  const nodesAndNames: Record<string, string> = {}
  Object.entries(components).forEach(([id, component]) => {
    const componentName = component.name
    if (component.componentSetId) {
      const componentSet = componentSets[component.componentSetId]
      // maybe a variant such as Direction=down, just keep the part after =
      const variantSeparatorIndex = componentName.indexOf("=")
      if (variantSeparatorIndex) {
        const variantName = componentName.substring(variantSeparatorIndex + 1)
        nodesAndNames[id] = [componentSet.name, variantName].join("-")
      } else {
        nodesAndNames[id] = [componentSet.name, componentName].join("-")
      }
    } else {
      nodesAndNames[id] = componentName
    }
  })
  return nodesAndNames
}

/** use the icon ids and names to fetch SVG URLs, then download each SVG and pass through svgr */

const generateIcons = async () => {
  const lines = [
    "/** This file is auto-generated by `yarn generate:icons` */",
    "",
  ]
  console.log("Fetching Figma icon artboard…")
  const nodesAndNames = await getIconNodesAndNames()
  const ids = Object.keys(nodesAndNames)
  const count = ids.length
  console.log(`Fetching ${count} icon SVG urls…`)
  const json: ImageResponse = await fetcher(
    `https://api.figma.com/v1/images/${FIGMA_ICONS_FILE_KEY}/?ids=${encodeURIComponent(
      ids.join(","),
    )}&format=svg`,
  )
  let index = 1
  for (const [id, url] of Object.entries(json.images)) {
    const name = nodesAndNames[id]
    const componentName = upperFirst(camelCase(name))
    console.log(
      `${index}/${count} Downloading icon SVG and creating component ${componentName}…`,
    )
    const reponse = await fetcher(url, true)
    const svgCode = await reponse.text()
    const componentCode = await svgCodeToIconComponentCode(svgCode)
    const componentFileName = path.join(OUTPUT_FOLDER, `${componentName}.tsx`)
    fs.writeFileSync(componentFileName, componentCode, "utf8")
    lines.push(
      `export { default as ${componentName} } from "./${componentName}";`,
    )
    index++
  }
  lines.push("")
  const fileContents = lines.join("\r\n")
  const indexFileName = path.join(OUTPUT_FOLDER, `index.ts`)
  fs.writeFileSync(indexFileName, fileContents, "utf8")
  console.log("Done")
}

;(async () => {
  await generateIcons()
})()
