/** This file is auto-generated by `yarn gen:icons` */

export { default as ArgentXLogoFull } from "./ArgentXLogoFull"
export { default as ArgentXLogo } from "./ArgentXLogo"
export { default as Github } from "./Github"
export { default as Discord } from "./Discord"
export { default as Twitter } from "./Twitter"
