name: Build
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      devnet:
        image: shardlabs/starknet-devnet:latest-seed0
        ports:
          - 5050:5050

    env:
      FILENAME: argent-extension-${{ github.ref_name }}
      FEATURE_PRIVACY_SETTINGS: "true"
      FEATURE_EXPERIMENTAL_SETTINGS: "true"
      FEATURE_BANXA: "true"
      FEATURE_LAYERSWAP: "true"
      FEATURE_ORBITER: "true"
      FEATURE_VERIFIED_DAPPS: "false"
      ARGENT_API_BASE_URL: ${{ secrets.ARGENT_API_BASE_URL }}
      ARGENT_TRANSACTION_REVIEW_API_BASE_URL: ${{ secrets.ARGENT_TRANSACTION_REVIEW_API_BASE_URL }}
      ARGENT_X_STATUS_URL: ${{ secrets.ARGENT_X_STATUS_URL }}
      ARGENT_EXPLORER_BASE_URL: ${{ secrets.ARGENT_EXPLORER_BASE_URL }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn setup

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn lerna run --scope @argent-x/extension build
        env:
          UPLOAD_SENTRY_SOURCEMAPS: false

      - name: Run unit tests
        run: yarn test:ci

      - name: Check bundlesize for chrome
        run: yarn run bundlewatch

      - name: Temporarily save build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: argentlabs/argent-x/packages/extension/dist
          retention-days: 1

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve saved build
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: argentlabs/argent-x/packages/extension/dist

      - name: Build load
        run: |
          tar -xvf build-artifact.tar
    needs: build
