name: Pre-release

on:
  push:
    branches:
      - prerelease/*

env:
  FEATURE_PRIVACY_SETTINGS: "true"
  FEATURE_EXPERIMENTAL_SETTINGS: "true"
  FEATURE_BANXA: "true"
  FEATURE_LAYERSWAP: "true"
  FEATURE_ORBITER: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      FILENAME: argent-extension-${{ github.ref_name }}
      SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      RAMP_API_KEY: ${{ secrets.RAMP_API_KEY }}
      UPLOAD_SENTRY_SOURCEMAPS: true
      ARGENT_API_BASE_URL: ${{ secrets.ARGENT_API_BASE_URL }}
      ARGENT_TRANSACTION_REVIEW_API_BASE_URL: ${{ secrets.ARGENT_TRANSACTION_REVIEW_API_BASE_URL }}
      ARGENT_X_STATUS_URL: ${{ secrets.ARGENT_X_STATUS_URL }}
      ARGENT_EXPLORER_BASE_URL: ${{ secrets.ARGENT_EXPLORER_BASE_URL }}
      SAFE_ENV_VARS: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Run e2e tests
        run: xvfb-run --auto-servernum yarn test:e2e

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: packages/extension/test-results/

      - run: yarn build
      - run: yarn --cwd packages/dapp export
      - name: Check bundlesize for chrome
        run: yarn run bundlewatch
      - name: Create chrome zip
        run: |
          cd packages/extension/dist
          zip -r $(echo "${{ env.FILENAME }}" | tr / -)-chrome.zip ./*
          mv $(echo "${{ env.FILENAME }}" | tr / -)-chrome.zip ../../../
          cd ../../../
      - name: Build Firefox version
        run: MANIFEST_VERSION=v2 yarn --cwd packages/extension build
      - name: Create firefox zip
        run: |
          cd packages/extension/dist
          zip -r $(echo "${{ env.FILENAME }}" | tr / -)-firefox.zip ./*
          mv $(echo "${{ env.FILENAME }}" | tr / -)-firefox.zip ../../../
          cd ../../../
      - name: Check bundlesize for firefox
        run: yarn run bundlewatch

      - name: Upload artifacts for chrome
        uses: actions/upload-artifact@v2
        with:
          name: chrome
          path: "*-chrome.zip"
          retention-days: 14
          if-no-files-found: error
      - name: Upload artifacts for firefox
        uses: actions/upload-artifact@v2
        with:
          name: firefox
          path: "*-firefox.zip"
          retention-days: 14
          if-no-files-found: error
