name: Run e2e tests
on:
  push:
    branches: [develop]
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FILENAME: argent-extension-${{ github.ref_name }}
      FEATURE_PRIVACY_SETTINGS: "true"
      FEATURE_EXPERIMENTAL_SETTINGS: "true"
      FEATURE_BANXA: "true"
      FEATURE_LAYERSWAP: "true"
      FEATURE_ORBITER: "true"
      FEATURE_VERIFIED_DAPPS: "false"
      ARGENT_API_BASE_URL: ${{ secrets.ARGENT_API_BASE_URL }}
      ARGENT_TRANSACTION_REVIEW_API_BASE_URL: ${{ secrets.ARGENT_TRANSACTION_REVIEW_API_BASE_URL }}
      ARGENT_X_STATUS_URL: ${{ secrets.ARGENT_X_STATUS_URL }}
      ARGENT_EXPLORER_BASE_URL: ${{ secrets.ARGENT_EXPLORER_BASE_URL }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build starknet-devnet
        run: docker build -f ./packages/extension/e2e/Dockerfile . --tag e2e-starknet-devnet:latest
      - name: Run starknet-devnet
        run: docker run -d -it --name devnet -p 5050:5050 e2e-starknet-devnet:latest

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn setup

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Build
        run: yarn lerna run --scope @argent-x/extension build
        env:
          UPLOAD_SENTRY_SOURCEMAPS: false

      - name: Check docker local network
        run: |
          CODE=`curl --write-out '%{http_code}' \
              --silent \
              --output /dev/null \
              --request GET \
              --url 'http://localhost:5050/is_alive' \
            `
          if [[ "$CODE" != "200" ]] 
          then
            echo "Local network is offline! $CODE"
            exit 1
          else
            echo "Local network is online."
          fi

      - name: Run e2e tests
        run: xvfb-run --auto-servernum yarn test:e2e

      - name: Stop starknet-devnet
        run: docker stop devnet

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            packages/extension/test-results/
            packages/extension/e2e/artifacts/playwright/
            packages/extension/e2e/artifacts/reports/
          retention-days: 5
