name: Build for Testing
on:
  workflow_call:
    secrets:
      ARGENT_API_BASE_URL:
        required: true
      ARGENT_TRANSACTION_REVIEW_API_BASE_URL:
        required: true
      ARGENT_X_STATUS_URL:
        required: true
      ARGENT_EXPLORER_BASE_URL:
        required: true
      GH_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.head_ref != '' && github.actor != 'dependabot[bot]' && github.event_name == 'pull_request'

    env:
      FILENAME: argent-extension-${{ github.ref_name }}
      FEATURE_PRIVACY_SETTINGS: "true"
      FEATURE_EXPERIMENTAL_SETTINGS: "true"
      FEATURE_BANXA: "true"
      FEATURE_LAYERSWAP: "true"
      FEATURE_ORBITER: "true"
      FEATURE_VERIFIED_DAPPS: "false"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn setup

      - name: Build
        run: yarn lerna run --scope @argent-x/extension build
        env:
          UPLOAD_SENTRY_SOURCEMAPS: false

      - name: Set filename prefix
        run: echo "FILENAME_PREFIX=$(echo ${{ env.FILENAME }}  | tr / -)" >> $GITHUB_ENV

      - name: Create chrome zip
        run: |
          cd packages/extension/dist
          zip -r ${{ env.FILENAME_PREFIX }}-chrome.zip ./*
          mv ${{ env.FILENAME_PREFIX }}-chrome.zip ../../../
          cd ../../../

      - name: Build Firefox version
        run: MANIFEST_VERSION=v2 yarn --cwd packages/extension build

      - name: Create firefox zip
        run: |
          cd packages/extension/dist
          zip -r ${{ env.FILENAME_PREFIX }}-firefox.zip ./*
          mv ${{ env.FILENAME_PREFIX }}-firefox.zip ../../../
          cd ../../../

      - name: Check bundlesize for firefox
        run: yarn run bundlewatch

      - name: Upload artifacts for firefox
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME_PREFIX }}-firefox.zip
          path: "*-firefox.zip"
          retention-days: 5

      - name: Upload artifacts for chrome
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME_PREFIX }}-chrome.zip
          path: "*-chrome.zip"
          retention-days: 5

      - name: Set GHA_BRANCH
        run: echo "GHA_BRANCH=$(echo $GITHUB_REF | awk -F / '{print $3}')" >> $GITHUB_ENV

      - name: comment PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          INPUT_REPO: ${{ env.GHA_BRANCH }}
          INPUT_OWNER: ${{ github.repository_owner }}
        run: |
          gh pr comment ${{ env.GHA_BRANCH }} --body "[Builds for local testing](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
